"""changes column name

Revision ID: 27b8f4b8a755
Revises: 46feef530032
Create Date: 2025-02-13 17:13:56.195664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27b8f4b8a755'
down_revision = '46feef530032'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient_bills', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patient_age', sa.Integer(), nullable=False))
        batch_op.drop_column('patiend_age')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient_bills', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patiend_age', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('patient_age')

    # ### end Alembic commands ###
