"""initial migration

Revision ID: 93893ba5670c
Revises: 
Create Date: 2025-04-16 18:28:13.386039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93893ba5670c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('org_name', sa.String(length=255), nullable=False),
    sa.Column('org_email', sa.String(length=255), nullable=False),
    sa.Column('org_phone_number', sa.String(length=255), nullable=False),
    sa.Column('org_type', sa.String(length=50), nullable=False),
    sa.Column('outstanding_balance', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('org_id'),
    sa.UniqueConstraint('org_email'),
    sa.UniqueConstraint('org_phone_number')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=255), nullable=False),
    sa.Column('user_role', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('adjustments',
    sa.Column('adjustment_id', sa.Integer(), nullable=False),
    sa.Column('adjusted_by', sa.Integer(), nullable=False),
    sa.Column('table_name', sa.String(length=255), nullable=False),
    sa.Column('column_name', sa.String(length=255), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('old_value', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('new_value', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('reason', sa.String(length=400), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['adjusted_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('adjustment_id')
    )
    op.create_table('auditlogs',
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('table_name', sa.String(length=255), nullable=False),
    sa.Column('column_name', sa.String(length=255), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('old_value', sa.String(length=255), nullable=False),
    sa.Column('new_value', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('patient_bills',
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.Column('patient_number', sa.String(length=50), nullable=False),
    sa.Column('patient_id', sa.String(length=15), nullable=False),
    sa.Column('patient_name', sa.String(length=255), nullable=False),
    sa.Column('patient_gender', sa.String(length=20), nullable=False),
    sa.Column('patient_age', sa.Integer(), nullable=True),
    sa.Column('patient_birthdate', sa.Date(), nullable=True),
    sa.Column('patient_phone_number', sa.String(length=50), nullable=False),
    sa.Column('bill_date', sa.Date(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('bill_type', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('amount >= 0', name='check_amount_positive'),
    sa.CheckConstraint('paid_amount >= 0', name='check_paid_amount_positive'),
    sa.CheckConstraint('patient_age >= 0', name='check_patient_age_positive'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.org_id'], ),
    sa.PrimaryKeyConstraint('bill_id')
    )
    with op.batch_alter_table('patient_bills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patient_bills_patient_number'), ['patient_number'], unique=True)

    op.create_table('transactions',
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(length=20), nullable=False),
    sa.Column('previous_outstanding_balance', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('transaction_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('final_balance', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('receipt_url', sa.String(length=300), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.CheckConstraint('transaction_amount >= 0', name='check_transaction_amount_positive'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.org_id'], ),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_table('paid_bills',
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.Column('patient_number', sa.String(length=50), nullable=False),
    sa.Column('patient_id', sa.String(length=15), nullable=False),
    sa.Column('patient_name', sa.String(length=255), nullable=False),
    sa.Column('patient_gender', sa.String(length=20), nullable=False),
    sa.Column('patient_age', sa.Integer(), nullable=True),
    sa.Column('patient_birthdate', sa.Date(), nullable=True),
    sa.Column('patient_phone_number', sa.String(length=50), nullable=False),
    sa.Column('bill_date', sa.Date(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('bill_type', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("status = 'paid'", name='check_status_paid'),
    sa.CheckConstraint('amount >= 0', name='check_amount_positive'),
    sa.CheckConstraint('paid_amount = amount', name='check_paid_bill_full_payment'),
    sa.CheckConstraint('paid_amount >= 0', name='check_paid_amount_positive'),
    sa.CheckConstraint('patient_age >= 0', name='check_patient_age_positive'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.org_id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.transaction_id'], ),
    sa.PrimaryKeyConstraint('bill_id')
    )
    with op.batch_alter_table('paid_bills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_paid_bills_patient_number'), ['patient_number'], unique=True)

    op.create_table('void_bills',
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.Column('voided_by', sa.Integer(), nullable=False),
    sa.Column('patient_number', sa.String(length=50), nullable=False),
    sa.Column('patient_id', sa.String(length=15), nullable=False),
    sa.Column('patient_name', sa.String(length=255), nullable=False),
    sa.Column('patient_gender', sa.String(length=20), nullable=False),
    sa.Column('patient_age', sa.Integer(), nullable=True),
    sa.Column('patient_birthdate', sa.Date(), nullable=True),
    sa.Column('patient_phone_number', sa.String(length=50), nullable=False),
    sa.Column('bill_date', sa.Date(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('bill_type', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('voided_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("status = 'void'", name='check_void_bill_status_paid'),
    sa.CheckConstraint('amount >= 0', name='check_amount_positive'),
    sa.CheckConstraint('paid_amount >= 0', name='check_paid_amount_positive'),
    sa.CheckConstraint('patient_age >= 0', name='check_patient_age_positive'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.org_id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.transaction_id'], ),
    sa.ForeignKeyConstraint(['voided_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('bill_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('void_bills')
    with op.batch_alter_table('paid_bills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_paid_bills_patient_number'))

    op.drop_table('paid_bills')
    op.drop_table('transactions')
    with op.batch_alter_table('patient_bills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patient_bills_patient_number'))

    op.drop_table('patient_bills')
    op.drop_table('auditlogs')
    op.drop_table('adjustments')
    op.drop_table('users')
    op.drop_table('organizations')
    # ### end Alembic commands ###
