"""remove unique index from patient_number

Revision ID: af641525a7bc
Revises: 93893ba5670c
Create Date: 2025-05-16 18:08:56.299134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af641525a7bc'
down_revision = '93893ba5670c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient_bills', schema=None) as batch_op:
        batch_op.drop_index('ix_patient_bills_patient_number')
        batch_op.create_index(batch_op.f('ix_patient_bills_patient_number'), ['patient_number'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient_bills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patient_bills_patient_number'))
        batch_op.create_index('ix_patient_bills_patient_number', ['patient_number'], unique=True)

    # ### end Alembic commands ###
